---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/4/10 14:17
---
-- ip_counter.lua
local _M = {}

local function format_number(count)
    if count >= 1000 then
        return string.format("%.1fk", count / 1000)
    else
        return tostring(count)
    end
end
function _M.print()
    local ip = ngx.var.remote_addr
    local counter = ngx.shared.ip_counter
    local uri = ngx.var.request_uri
    local count = counter:get(ip) or 0
    -- 忽略对 /favicon.ico 的计数
    if uri ~= "/favicon.ico" then
        count = count + 1
        counter:set(ip, count)
    end
    local formatted_count = format_number(count)
    ngx.say('<html>')
    ngx.say('<head><style>')
    ngx.say('body { font-size: 16px; }')
    ngx.say('.ip { color: red; }')
    ngx.say('.domain { color: darkorange; }')
    ngx.say('.uri { color: green; }')
    ngx.say('.method { color: blue; }')
    ngx.say('.useragent { color: purple; }')
    ngx.say('</style></head>')
    ngx.say('<body>')
    ngx.say('<p class="ip">Client IP: ', ngx.var.remote_addr, '</p>')
    ngx.say('<p>Number of visits: ', formatted_count, '</p>')
    ngx.say('<p class="domain">Host: ', ngx.var.host, '</p>')
    ngx.say('<p class="uri">Request URI: ', ngx.var.request_uri, '</p>')
    ngx.say('<p class="method">Request Method: ', ngx.var.request_method, '</p>')
    ngx.say('<p class="useragent">User-Agent: ', ngx.var.http_user_agent, '</p>')
    ngx.say('</body></html>')
end

return _M
