---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/4/10 15:00
---
-- 文件路径：/usr/local/openresty/nginx/lua/server_header.lua

local _M = {}

function _M.random_server_header()
    local servers = {
        "Apache/2.4.41 (Unix)",
        "Microsoft-IIS/10.0",
        "nginx/1.18.0",
        "Cloudflare",
        "GWS",
        "lighttpd/1.4.53",
        "Kestrel",
        "Caddy",
        "Jetty/9.4.35",
        "Tomcat/9.0.39",
        "IBM_HTTP_Server",
        "Oracle-Application-Server-11g",
        "Node.js",
        "Django/3.1.4",
        "CustomServer/1.0.0",
        "AkamaiGHost",
        "AmazonS3",
        "Apache-Coyote/1.1",
        "nginx/1.16.1 (Ubuntu)",
        "squid/3.5.12",
        "ATS/8.0.5"
    }
    local random_index = math.random(#servers)
    return servers[random_index]
end

return _M
