---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/8 17:22
---
local aes = require "resty.aes"
local cjson = require("cjson")
-- 密钥和IV
local key = "adfg1234asdfqwe2"
local iv = "0000000000000000"

local _M = {}  -- 创建一个模块表
-- 创建 AES 实例
local aes_128 = aes:new(key, nil, aes.cipher(128, "cbc"), { iv = iv })
function _M.decrypt(ciphertext)
    -- base64解码
    local decrypted = ngx.decode_base64(ciphertext)
    -- 解密
    local plaintext = aes_128:decrypt(decrypted)
    return plaintext
end



function _M.encrypt(plaintext)
    -- 加密
    local encrypted = aes_128:encrypt(plaintext)
    local ciphertext = ngx.encode_base64(encrypted, true)
    return ciphertext
end

return _M