---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/8 16:35
---
local AesTool = require "aes_tool"
-- 从请求中获取原始请求体
local request_body = ngx.req.get_body_data()
---- 执行加密操作，例如使用加密库或算法
local encrypted_body = AesTool.decrypt(request_body)
---- 替换请求体为加密后的内容
ngx.req.set_body_data(encrypted_body)
return true

