---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/2/7 17:37
---

local newProductor

function productor()
    local i = 0
    while i<=1000000 do
        i = i + 1
        send(i)     -- 将生产的物品发送给消费者
    end
end

function consumer()
    while true do
        local i = receive()     -- 从生产者那里得到物品
        print(i)
    end
end

function receive()
    local status, value = coroutine.resume(newProductor)
    return value
end

function send(x)
    coroutine.yield(x)     -- x表示需要发送的值，值返回以后，就挂起该协同程序
end

-- 启动程序
newProductor = coroutine.create(productor)
consumer()