---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/12 16:01
---
local cjson = require "cjson"
local jwt = require "resty.jwt"
local secret_key = "lua-resty-jwt"
local jwt_obj = {
    header = { typ = "JWT", alg = "HS256" },
    payload = { foo = "bar" }
}
local jwt_token = jwt:sign(secret_key, jwt_obj)
ngx.say(jwt_token)