---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/10 11:07
---
logdir = "G:/openresty-1.21.4.1-win64/logs/debug"
logpath = logdir
local _M = {}  -- 创建一个模块表


function _M.log(line)
    ngx.log(ngx.ERR,"==================")
    --local realIp = getClientIp()
    --local ua = ngx.var.http_user_agent
    --local servername = ngx.var.server_name
    local time = ngx.localtime()
    --if ua then
    --    line = realIp .. " [" .. time .. "] \"" .. method .. " " .. servername .. url .. "\" \"" .. data .. "\"  \"" .. ua .. "\"\n"
    --else
    --    line = realIp .. " [" .. time .. "] \"" .. method .. " " .. servername .. url .. "\" \"" .. data .. "\"\n"
    --end
    line = " [" .. time .. "] \"" ..line.. "\"\n"
    local filename = logpath .. '/' .. "debug" .. "_" .. ngx.today() .. "_sec.log"
    write(filename, line)
end
function write(logfile, msg)
    ngx.log(ngx.ERR,"============+++++++++++++++++======")
    local fd = io.open(logfile, "ab")
    if fd == nil then
        return
    end
    fd:write(msg)
    fd:flush()
    fd:close()
end
return _M