---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/2/7 13:47
---
local demo = require('demo')
d = demo.connect()
d:get('a')
d.call = function(cmd, ...)
    return assert(loadstring('return d:'.. string.lower(cmd) ..'(...)'))(...)
end
d.call('GET','b')

loadstring('d:get(...)')("c","c")