---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/9/28 16:43
---
---
package.path ='F:/IdeaProject/openresty/openresty/src/main/lua/?.lua;;'
local Database = require "mysql_db"
local cjson = require("cjson");
-- 创建数据库连接
local db, err = Database.new()
if not db then
    ngx.say("Failed to connect to the database: ", err)
    return
end

-- 执行查询
local sql = "SELECT * FROM users"
local res, err = Database.query(db, sql)
if not res then
    ngx.say("Failed to execute query: ", err)
else
    ngx.log(ngx.ERR,"res type :",type(res))
    -- 处理查询结果
    for i, row in ipairs(res) do
        ngx.say("TYPE ",type(row))
        ngx.log(ngx.ERR,"row:",cjson.encode(row))
        ngx.log(ngx.ERR,"row concat:",table.concat(row))
        ngx.say("Row ", i, "role: ", row['role'])
        ngx.say("Row ", i, ": ", cjson.encode(row))
    end
end
-- 释放数据库连接
Database.close(db)

