---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/9 14:49
---
local pkey = require("resty.openssl.pkey")
--
-- 读取 RSA 公钥文件
local public_key_path = "e:/rsa/rsaPublicKey.pem"
local public_key_file, err = io.open(public_key_path, "r")
if not public_key_file then
    ngx.log(ngx.ERR, "Failed to open public key file: ", err)
    ngx.exit(500)
end

local public_key_pem = public_key_file:read("*a")
public_key_file:close()

-- 读取 RSA 私钥文件
local private_key_path = "e:/rsa/rsaPrivateKey.pem"
local private_key_file, err = io.open(private_key_path, "r")
if not private_key_file then
    ngx.log(ngx.ERR, "Failed to open private key file: ", err)
    ngx.exit(500)
end

local private_key_pem = private_key_file:read("*a")
private_key_file:close()

local _M = {}  -- 创建一个模块表
--创建公私钥
local privkey, err = pkey.new(private_key_pem)
local pubkey, err = pkey.new(public_key_pem)
function _M.decrypt(ciphertext)
    -- base64解码
    local decrypted = ngx.decode_base64(ciphertext)
    -- 解密
    local plaintext = privkey:decrypt(decrypted, pkey.PADDINGS.RSA_PKCS1_PADDING)
    return plaintext
end

function _M.encrypt(plaintext)
    -- 加密
    local encrypted = pubkey:encrypt(plaintext, pkey.PADDINGS.RSA_PKCS1_PADDING)
    local ciphertext = ngx.encode_base64(encrypted, true)
    return ciphertext
end

return _M