---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/8 16:35
---
local openssl_rsa = require "resty.openssl.rsa"

-- 加载 RSA 私钥文件
local private_key, err = openssl_rsa:new({ private_key = "e:/rsa/rsaPrivateKey.pem" })
if not private_key then
    ngx.log(ngx.ERR, "Failed to load private key: ", err)
    ngx.exit(500)
end

-- 加密数据
local data_to_encrypt = "Hello, OpenResty!"
local encrypted_data, err = private_key:encrypt(data_to_encrypt)
if not encrypted_data then
    ngx.log(ngx.ERR, "Failed to encrypt data: ", err)
    ngx.exit(500)
end