---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/8 16:35
---
local openssl_rsa = require "resty.openssl.rsa"

-- 加载 RSA 公钥文件
local public_key, err = openssl_rsa:new({ public_key = "e:/rsa/rsaPublicKey.pem" })
if not public_key then
    ngx.log(ngx.ERR, "Failed to load public key: ", err)
    ngx.exit(500)
end

-- 从请求中获取原始请求体
local request_body = ngx.req.get_body_data()

-- 解密数据
local decrypted_data, err = public_key:decrypt(request_body)
if not decrypted_data then
    ngx.log(ngx.ERR, "Failed to decrypt data: ", err)
    ngx.exit(500)
    return false
end

---- 替换请求体为加密后的内容
ngx.req.set_body_data(encrypted_body)
return true


