---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/9/27 10:53
---
---数据响应类型JSON
ngx.header.content_type = "application/json;charset=utf8"
success = {}
success['code'] = 200
success['msg'] = 'SUCCESS'
success['success'] = true
local cjson = require("cjson");
data = {}
local uri = ngx.var.uri
data['uri'] =uri
local args = ngx.var.args
data['args'] =args
local remote_addr = ngx.var.remote_addr
data['remote_addr'] =remote_addr
local remote_port = ngx.var.remote_port
data['remote_port'] =remote_port
local http_referer = ngx.var.http_referer
data['http_referer'] =http_referer
local clientIP = ngx.req.get_headers()["X-Real-IP"]
if clientIP == nil then
    clientIP = ngx.req.get_headers()["x_forwarded_for"]
end if clientIP == nil then
    clientIP = ngx.var.remote_addr
end
data['clientIP'] =clientIP
success['data'] =data
ngx.say(cjson.encode(success))