---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/12 17:47
---//gcc -shared -o myffi.dll myffi.c
--#include <stdio.h>
--int add(int x, int y)
--{
--    return x + y;
--}
--int main() {
--    int res = add(1, 2);
--    printf( "test-%d",res);
--    return 0;
--}
---
local ffi = require("ffi")
local C = ffi.C
local myffi = ffi.load('F:/IdeaProject/openresty/openresty/src/main/lua/dll/myffi.dll')
ffi.cdef([[
int add(int x, int y);   /* don't forget to declare */
int printf(const char *fmt, ...);
]])


-- 要计算的数据
local res =  myffi.add(1, 2)
print(res)  -- output: 3   Note: please use luajit to run this script.
ffi.C.printf("Hello %s!", "world")