---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/10/12 17:47
---
local ffi = require("ffi")
local myffi = ffi.load('F:/IdeaProject/openresty/openresty/src/main/lua/myffi.dll')
ffi.cdef([[
int add(int x, int y);   /* don't forget to declare */
]])


-- 要计算的数据
local res = myffi.add(1, 2)
print(res)  -- output: 3   Note: please use luajit to run this script.
