---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/2/8 10:24
---
require "luasql.mysql"
local cjson = require "cjson"
--创建环境对象
env = luasql.mysql()

--连接数据库
conn = env:connect("account","root","123456","127.0.0.1",3306)

--设置数据库的编码格式
conn:execute"SET NAMES UTF8"

--执行数据库操作
cur = conn:execute("select * from test limit 1")

row = cur:fetch({},"a")

--文件对象的创建
file = io.open("d:/test.txt","w+");

while row do
    --var = string.format("%d %s\n", row.id, row.name)
    --for k, v in pairs(row) do
    --    str = string.format("%s %s\n", k, cjson.encode(v))
    --    print(str)
    --end
    var = cjson.encode(row)
    print(var)

    file:write(var..'\n')
--
    row = cur:fetch(row,"a")
end


file:close()  --关闭文件对象
conn:close()  --关闭数据库连接
env:close()   --关闭数据库环境
