---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/9/21 15:47
---

function split(inputstr, sep)
    local t = {}
    for str in string.gmatch(inputstr, "([^" .. sep .. "]+)") do
        table.insert(t, str)
    end
    return t
end

local input = "Hello,World,This,is,a,test"
local separator = ","
local result = split(input, separator)
print(result)
for i, v in ipairs(result) do
    print(i, v)
end
